/**
 * The cloud noise volume (Schneider 2015): tileable Perlin–Worley and Worley fBm in one 128³
 * texture, generated by a compute pass once at init. Clouds sample it at `noiseBinding` with a
 * repeating trilinear sampler, so it tiles seamlessly at every scale they use.
 */

import common from '../shaders/common.wgsl'
import noise from '../shaders/noise.wgsl'
import { shader } from '../shader'
import { createComputePass, type ComputePass } from './compute'
import type { PassContext } from './pass'

export const noiseSize = { width: 128, height: 128, depthOrArrayLayers: 128 } as const
export const noiseFormat: GPUTextureFormat = 'rgba8unorm'

/** Where shaders that include `clouds.wgsl` read the volume; its sampler follows. */
const noiseBinding = 5

/** Runs once: the volume never changes. It writes its only binding, 0, so it needs no uniforms. */
export function createNoisePass(context: PassContext, output: GPUTextureView): Promise<ComputePass> {
  const { width, height, depthOrArrayLayers } = noiseSize
  return createComputePass(context, {
    label: 'noise',
    module: shader(context.device, 'noise', [common, noise]),
    entries: [{ binding: 0, resource: output }],
    workgroups: [width / 4, height / 4, depthOrArrayLayers / 4],
  })
}

/** Bind group entries for the noise volume and a trilinear sampler that repeats it. */
export function noiseEntries(device: GPUDevice, volume: GPUTextureView): GPUBindGroupEntry[] {
  const sampler = device.createSampler({
    label: 'noise',
    addressModeU: 'repeat',
    addressModeV: 'repeat',
    addressModeW: 'repeat',
    magFilter: 'linear',
    minFilter: 'linear',
  })
  return [
    { binding: noiseBinding, resource: volume },
    { binding: noiseBinding + 1, resource: sampler },
  ]
}
