// The stars as they are seen this frame, in one buffer, written by the `stars` pass once per star
// and read by `post` for every pixel their light reaches: first the catalogue's CATALOGUE_STARS,
// then one slot per cell of the faint field's cube map, empty where a cell holds no star.
// CATALOGUE_STARS, CATALOGUE_CELLS and FIELD_CELLS (cells per face edge of the faint field; a
// pixel looks at the 2 × 2 nearest, so a star's light must reach no further than half a cell)
// are generated by `sky/catalogue.ts`.

// A star as it is seen this frame: where it falls on the display, how far out its light is
// drawn, and that light (radiance per unit share of it in a pixel).
struct SeenStar {
  centre: vec2f, // display pixels
  reach: f32, // display pixels, 0 when out of view or empty
  light: vec3f,
}

fn faintSlot(face: u32, cell: vec2u) -> u32 {
  return CATALOGUE_STARS + cubeCellIndex(face, cell, FIELD_CELLS);
}
